server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
  # If you want to use basic auth, you can set it as follows.
  # - url: https://<LOKI_HOST>/loki/api/v1/push
  #   basic_auth:
  #     username: <USERNAME>
  #     password: <PASSWORD>

scrape_configs:
  - job_name: logman
    static_configs:
      - targets:
          - localhost
        labels:
          job: delta
          __path__: /var/logs/*.log
          environment: production
