version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    volumes:
      - logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1

  loki:
    image: grafana/loki
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail
    volumes:
      - logs:/var/logs
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml

volumes:
  logs:
